spring.application.name=HobbyCircles
spring.datasource.url=jdbc:postgresql://ep-purple-surf-atr1krfr-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_AtxyQ9fGiM3e&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update
#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
