spring.application.name=HobbyCirclesspring.datasource.url=jdbc:postgresql://ep-soft-darkness-ah8yqezt-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_XYam2qEPTwB8&sslmode=require&channelBinding=require

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
