<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Provider Profile</title>

    <link rel="stylesheet" href="/style.css">

</head>

<body>

<nav class="navbar">

    <div class="logo-text">
        HobbyCircles
    </div>

<div class="nav-links">
    <a href="/dashboard">Dashboard</a>
    <a href="/provider-profile" class="active">Profile</a>
    <a href="/create-event">Create Event</a>
    <a href="/my-events">My Events</a>
    <a href="/reviews">Reviews</a>
</div>

</nav>

<div class="container">

    <h1>Create Your Profile ✨</h1>

 <div class="form-card small-form">

    <label>Name:</label>
    <input type="text" placeholder="e.g. John Doe">

    <label>Email:</label>
    <input type="text" placeholder="e.g. @gmail.com, @icloud.com ">

    <label>Interest/Hobbies:</label>
    <textarea placeholder="Vlogging, Music, Anime, etc."></textarea>

    <label>Description:</label>
    <textarea placeholder="Tell users about your events..."></textarea>

    <label>Location</label>
    <input type="text" placeholder="City/Area">

    <button class="btn primary-btn">Create Profile</button>

</div>

</div>
    
</body>
</html>
